/**
 * IndexedDB persistence for imported GTFS feeds.
 *
 * Each system's records live under stores keyed by prefixed IDs so multiple
 * feeds can coexist without collision. Deleting a system is a single bulk-
 * delete pass keyed by the systemId index on every store.
 *
 * Schema evolution lives in the {@link MIGRATIONS} table below — each bump
 * is a `{ version, run(db, tx) }` entry and `upgrade(...)` just replays the
 * applicable steps between `oldVersion` and the current `DB_VERSION`. Add
 * new steps to the end of the array; never edit a released step (users'
 * databases already ran it).
 */

import {
    type DBSchema,
    type IDBPDatabase,
    type IDBPTransaction,
    openDB,
    type StoreNames,
} from "idb";
import { toast } from "react-toastify";

import type {
    Footpath,
    TransitRoute,
    TransitService,
    TransitStop,
    TransitSystem,
    TransitTrip,
    TransitTripStopTimes,
} from "./types";

const DB_NAME = "jetlag-transit";

interface TransitDBSchema extends DBSchema {
    systems: {
        key: string;
        value: TransitSystem;
    };
    stops: {
        key: string;
        value: TransitStop;
        indexes: { "by-system": string };
    };
    routes: {
        key: string;
        value: TransitRoute;
        indexes: { "by-system": string };
    };
    trips: {
        key: string;
        value: TransitTrip;
        indexes: { "by-system": string; "by-route": string };
    };
    stopTimes: {
        key: string;
        value: TransitTripStopTimes;
        indexes: { "by-system": string };
    };
    services: {
        key: string;
        value: TransitService;
        indexes: { "by-system": string };
    };
    /** GTFS-provided transfers.txt. */
    transfersGtfs: {
        key: [string, string];
        value: Footpath;
        indexes: { "by-from": string; "by-system": string };
    };
    /** Auto-generated by proximity. Recomputed when systems change. */
    transfersAuto: {
        key: [string, string];
        value: Footpath;
        indexes: { "by-from": string };
    };
}

export type TransitDB = IDBPDatabase<TransitDBSchema>;

/**
 * One schema migration step. `run` executes inside the `versionchange`
 * transaction — callers can use either `db` (store creation / deletion) or
 * `tx` (data rewrites on existing stores).
 *
 * Steps must be idempotent across repeated failed upgrades: IDB aborts the
 * whole `versionchange` transaction on throw, so a retry will re-enter at
 * the same `oldVersion`. Guard with `db.objectStoreNames.contains(...)`
 * when adding stores/indexes that another path might also create.
 */
interface MigrationStep {
    version: number;
    name: string;
    run(
        db: IDBPDatabase<TransitDBSchema>,
        tx: IDBPTransaction<
            TransitDBSchema,
            StoreNames<TransitDBSchema>[],
            "versionchange"
        >,
    ): void | Promise<void>;
}

const MIGRATIONS: MigrationStep[] = [
    {
        version: 1,
        name: "initial schema",
        run(db) {
            db.createObjectStore("systems", { keyPath: "id" });

            const stops = db.createObjectStore("stops", { keyPath: "id" });
            stops.createIndex("by-system", "systemId");

            const routes = db.createObjectStore("routes", {
                keyPath: "id",
            });
            routes.createIndex("by-system", "systemId");

            const trips = db.createObjectStore("trips", { keyPath: "id" });
            trips.createIndex("by-system", "systemId");
            trips.createIndex("by-route", "routeId");

            const stopTimes = db.createObjectStore("stopTimes", {
                keyPath: "tripId",
            });
            stopTimes.createIndex("by-system", "systemId");

            const services = db.createObjectStore("services", {
                keyPath: "id",
            });
            services.createIndex("by-system", "systemId");

            const transfersGtfs = db.createObjectStore("transfersGtfs", {
                keyPath: ["fromStopId", "toStopId"],
            });
            transfersGtfs.createIndex("by-from", "fromStopId");
            // For bulk-delete we need to know which system a transfer
            // belongs to — derived from the fromStopId prefix, but an
            // explicit index is faster than string parsing.
            transfersGtfs.createIndex("by-system", "fromStopId");

            const transfersAuto = db.createObjectStore("transfersAuto", {
                keyPath: ["fromStopId", "toStopId"],
            });
            transfersAuto.createIndex("by-from", "fromStopId");
        },
    },
    // Future migration steps go here:
    // {
    //     version: 2,
    //     name: "add parent_station index on stops",
    //     run(db, tx) {
    //         tx.objectStore("stops").createIndex(
    //             "by-parent", "parentStationId", { unique: false },
    //         );
    //     },
    // },
];

/**
 * Current DB version = highest version in {@link MIGRATIONS}. Keeping this
 * derived means you can't forget to bump it when adding a step.
 */
const DB_VERSION = MIGRATIONS.reduce((max, m) => Math.max(max, m.version), 0);

let dbPromise: Promise<TransitDB> | null = null;

export function openTransitDB(): Promise<TransitDB> {
    if (dbPromise) return dbPromise;
    dbPromise = openDB<TransitDBSchema>(DB_NAME, DB_VERSION, {
        upgrade(db, oldVersion, _newVersion, tx) {
            // Replay every migration step strictly newer than what the
            // user's DB already has. Steps run in ascending version order.
            const sorted = [...MIGRATIONS].sort(
                (a, b) => a.version - b.version,
            );
            for (const step of sorted) {
                if (step.version <= oldVersion) continue;
                try {
                    step.run(db, tx);
                } catch (err) {
                    console.error(
                        `IDB migration failed at v${step.version} (${step.name}):`,
                        err,
                    );
                    // Rethrow so IDB aborts the versionchange transaction
                    // and the user's data stays on the previous version
                    // instead of ending up half-migrated.
                    throw err;
                }
            }
        },
        blocked(currentVersion, blockedVersion) {
            // Another tab of the app still has an older connection open,
            // preventing our version bump. Ask the user to close it.
            console.log(
                `IDB upgrade blocked: v${currentVersion} → v${blockedVersion}`,
            );
            toast.warning(
                "A newer version of the app is ready — close other tabs of this site to apply it.",
                {
                    toastId: "idb-upgrade-blocked",
                    autoClose: false,
                },
            );
        },
        blocking(currentVersion, blockedVersion) {
            // This tab holds the old connection; another tab wants to
            // upgrade. Close our connection so they can proceed; the
            // next openTransitDB() call from this tab will re-open at
            // the new version.
            console.log(
                `Closing old IDB connection to unblock upgrade: v${currentVersion} → v${blockedVersion}`,
            );
            // The `db` param isn't handed to us here; rely on idb's
            // default close-on-blocking via resetting the cached promise.
            dbPromise = null;
        },
        terminated() {
            // Browser forcibly closed the DB (quota eviction, etc.).
            // Reset the cache so the next call retries.
            console.log("IDB connection terminated unexpectedly");
            dbPromise = null;
            toast.error(
                "Local transit storage was closed unexpectedly. Reload to retry.",
                {
                    toastId: "idb-terminated",
                    autoClose: 8000,
                },
            );
        },
    }).catch((err: unknown) => {
        // openDB failed outright — usually SecurityError (private mode /
        // blocked storage), QuotaExceededError (low disk), or corruption.
        console.error("Failed to open transit DB:", err);
        toast.error(
            "Couldn't open local transit storage. Private mode, low disk, or a corrupted database may be the cause.",
            {
                toastId: "idb-open-failed",
                autoClose: 8000,
            },
        );
        // Null out so a future call can retry (e.g. after the user
        // exits private mode or frees disk space).
        dbPromise = null;
        throw err;
    });
    return dbPromise;
}

// ---------------------------------------------------------------------------
// System CRUD
// ---------------------------------------------------------------------------

export async function listSystems(): Promise<TransitSystem[]> {
    const db = await openTransitDB();
    return db.getAll("systems");
}

/**
 * Bulk-delete everything belonging to a system. Runs in a single transaction
 * so the UI never sees a half-deleted state.
 *
 * Auto-transfers are NOT cleared here — callers should re-run the auto-
 * transfer builder after any add/remove since the graph crosses systems.
 */
export async function deleteSystem(systemId: string): Promise<void> {
    const db = await openTransitDB();
    const tx = db.transaction(
        [
            "systems",
            "stops",
            "routes",
            "trips",
            "stopTimes",
            "services",
            "transfersGtfs",
        ],
        "readwrite",
    );

    await tx.objectStore("systems").delete(systemId);
    await deleteByIndex(tx.objectStore("stops").index("by-system"), systemId);
    await deleteByIndex(tx.objectStore("routes").index("by-system"), systemId);
    await deleteByIndex(tx.objectStore("trips").index("by-system"), systemId);
    await deleteByIndex(
        tx.objectStore("stopTimes").index("by-system"),
        systemId,
    );
    await deleteByIndex(
        tx.objectStore("services").index("by-system"),
        systemId,
    );
    // transfersGtfs: by-system is indexed on fromStopId which is prefixed with
    // the systemId. Cursor over the index's keyRange for that prefix.
    const prefix = `${systemId}:`;
    const range = IDBKeyRange.bound(prefix, `${prefix}\uffff`);
    let cursor = await tx
        .objectStore("transfersGtfs")
        .index("by-from")
        .openCursor(range);
    while (cursor) {
        await cursor.delete();
        cursor = await cursor.continue();
    }

    await tx.done;
}

async function deleteByIndex(index: any, systemId: string): Promise<void> {
    let cursor = await index.openCursor(IDBKeyRange.only(systemId));
    while (cursor) {
        await cursor.delete();
        cursor = await cursor.continue();
    }
}

// ---------------------------------------------------------------------------
// Bulk writes for import
// ---------------------------------------------------------------------------

/**
 * Write everything for one system atomically. If any put fails the whole
 * transaction rolls back — we never leave a half-imported feed on disk.
 */
export async function writeSystemBulk(opts: {
    system: TransitSystem;
    stops: TransitStop[];
    routes: TransitRoute[];
    trips: TransitTrip[];
    stopTimes: TransitTripStopTimes[];
    services: TransitService[];
    transfers: Footpath[];
}): Promise<void> {
    const db = await openTransitDB();
    const tx = db.transaction(
        [
            "systems",
            "stops",
            "routes",
            "trips",
            "stopTimes",
            "services",
            "transfersGtfs",
        ],
        "readwrite",
    );

    const put = <T>(store: string, items: T[]) => {
        const os = (tx as any).objectStore(store);
        return Promise.all(items.map((item) => os.put(item)));
    };

    await tx.objectStore("systems").put(opts.system);
    await put("stops", opts.stops);
    await put("routes", opts.routes);
    await put("trips", opts.trips);
    await put("stopTimes", opts.stopTimes);
    await put("services", opts.services);
    await put("transfersGtfs", opts.transfers);

    await tx.done;
}

// ---------------------------------------------------------------------------
// Reads used by routing
// ---------------------------------------------------------------------------

export async function getAllStops(
    systemIds?: string[],
): Promise<TransitStop[]> {
    const db = await openTransitDB();
    if (!systemIds || systemIds.length === 0) {
        return db.getAll("stops");
    }
    const out: TransitStop[] = [];
    for (const sid of systemIds) {
        out.push(...(await db.getAllFromIndex("stops", "by-system", sid)));
    }
    return out;
}

export async function getAllStopTimes(
    systemIds?: string[],
): Promise<TransitTripStopTimes[]> {
    const db = await openTransitDB();
    if (!systemIds || systemIds.length === 0) {
        return db.getAll("stopTimes");
    }
    const out: TransitTripStopTimes[] = [];
    for (const sid of systemIds) {
        out.push(...(await db.getAllFromIndex("stopTimes", "by-system", sid)));
    }
    return out;
}

export async function getAllTrips(
    systemIds?: string[],
): Promise<TransitTrip[]> {
    const db = await openTransitDB();
    if (!systemIds || systemIds.length === 0) {
        return db.getAll("trips");
    }
    const out: TransitTrip[] = [];
    for (const sid of systemIds) {
        out.push(...(await db.getAllFromIndex("trips", "by-system", sid)));
    }
    return out;
}

export async function getAllRoutes(
    systemIds?: string[],
): Promise<TransitRoute[]> {
    const db = await openTransitDB();
    if (!systemIds || systemIds.length === 0) {
        return db.getAll("routes");
    }
    const out: TransitRoute[] = [];
    for (const sid of systemIds) {
        out.push(...(await db.getAllFromIndex("routes", "by-system", sid)));
    }
    return out;
}

export async function getAllServices(
    systemIds?: string[],
): Promise<TransitService[]> {
    const db = await openTransitDB();
    if (!systemIds || systemIds.length === 0) {
        return db.getAll("services");
    }
    const out: TransitService[] = [];
    for (const sid of systemIds) {
        out.push(...(await db.getAllFromIndex("services", "by-system", sid)));
    }
    return out;
}

export async function getAllTransfers(): Promise<Footpath[]> {
    const db = await openTransitDB();
    const [gtfs, auto] = await Promise.all([
        db.getAll("transfersGtfs"),
        db.getAll("transfersAuto"),
    ]);
    return [...gtfs, ...auto];
}

// ---------------------------------------------------------------------------
// Auto-transfer management
// ---------------------------------------------------------------------------

export async function replaceAutoTransfers(
    transfers: Footpath[],
): Promise<void> {
    const db = await openTransitDB();
    const tx = db.transaction("transfersAuto", "readwrite");
    await tx.objectStore("transfersAuto").clear();
    await Promise.all(
        transfers.map((t) => tx.objectStore("transfersAuto").put(t)),
    );
    await tx.done;
}

// ---------------------------------------------------------------------------
// Diagnostics — used by the Transit Systems dialog to show space usage
// ---------------------------------------------------------------------------

export async function estimateUsage(): Promise<{
    usage?: number;
    quota?: number;
}> {
    if (typeof navigator === "undefined" || !navigator.storage?.estimate) {
        return {};
    }
    const { usage, quota } = await navigator.storage.estimate();
    return { usage, quota };
}
