/**
 * IndexedDB persistence for imported GTFS feeds.
 *
 * Each system's records live under stores keyed by prefixed IDs so multiple
 * feeds can coexist without collision. Deleting a system is a single bulk-
 * delete pass keyed by the systemId index on every store.
 *
 * Schema version bumps must be handled in `upgrade` below — users will have
 * real imported data we don't want to silently drop.
 */

import { type DBSchema, type IDBPDatabase, openDB } from "idb";

import type {
    Footpath,
    TransitRoute,
    TransitService,
    TransitStop,
    TransitSystem,
    TransitTrip,
    TransitTripStopTimes,
} from "./types";

const DB_NAME = "jetlag-transit";
const DB_VERSION = 1;

interface TransitDBSchema extends DBSchema {
    systems: {
        key: string;
        value: TransitSystem;
    };
    stops: {
        key: string;
        value: TransitStop;
        indexes: { "by-system": string };
    };
    routes: {
        key: string;
        value: TransitRoute;
        indexes: { "by-system": string };
    };
    trips: {
        key: string;
        value: TransitTrip;
        indexes: { "by-system": string; "by-route": string };
    };
    stopTimes: {
        key: string;
        value: TransitTripStopTimes;
        indexes: { "by-system": string };
    };
    services: {
        key: string;
        value: TransitService;
        indexes: { "by-system": string };
    };
    /** GTFS-provided transfers.txt. */
    transfersGtfs: {
        key: [string, string];
        value: Footpath;
        indexes: { "by-from": string; "by-system": string };
    };
    /** Auto-generated by proximity. Recomputed when systems change. */
    transfersAuto: {
        key: [string, string];
        value: Footpath;
        indexes: { "by-from": string };
    };
}

export type TransitDB = IDBPDatabase<TransitDBSchema>;

let dbPromise: Promise<TransitDB> | null = null;

export function openTransitDB(): Promise<TransitDB> {
    if (dbPromise) return dbPromise;
    dbPromise = openDB<TransitDBSchema>(DB_NAME, DB_VERSION, {
        upgrade(db, oldVersion) {
            // Fresh install.
            if (oldVersion < 1) {
                db.createObjectStore("systems", { keyPath: "id" });

                const stops = db.createObjectStore("stops", { keyPath: "id" });
                stops.createIndex("by-system", "systemId");

                const routes = db.createObjectStore("routes", {
                    keyPath: "id",
                });
                routes.createIndex("by-system", "systemId");

                const trips = db.createObjectStore("trips", { keyPath: "id" });
                trips.createIndex("by-system", "systemId");
                trips.createIndex("by-route", "routeId");

                const stopTimes = db.createObjectStore("stopTimes", {
                    keyPath: "tripId",
                });
                stopTimes.createIndex("by-system", "systemId");

                const services = db.createObjectStore("services", {
                    keyPath: "id",
                });
                services.createIndex("by-system", "systemId");

                const transfersGtfs = db.createObjectStore("transfersGtfs", {
                    keyPath: ["fromStopId", "toStopId"],
                });
                transfersGtfs.createIndex("by-from", "fromStopId");
                // For bulk-delete we need to know which system a transfer
                // belongs to — derived from the fromStopId prefix, but an
                // explicit index is faster than string parsing.
                transfersGtfs.createIndex("by-system", "fromStopId");

                const transfersAuto = db.createObjectStore("transfersAuto", {
                    keyPath: ["fromStopId", "toStopId"],
                });
                transfersAuto.createIndex("by-from", "fromStopId");
            }
        },
    });
    return dbPromise;
}

// ---------------------------------------------------------------------------
// System CRUD
// ---------------------------------------------------------------------------

export async function listSystems(): Promise<TransitSystem[]> {
    const db = await openTransitDB();
    return db.getAll("systems");
}

export async function getSystem(id: string): Promise<TransitSystem | undefined> {
    const db = await openTransitDB();
    return db.get("systems", id);
}

export async function saveSystem(system: TransitSystem): Promise<void> {
    const db = await openTransitDB();
    await db.put("systems", system);
}

/**
 * Bulk-delete everything belonging to a system. Runs in a single transaction
 * so the UI never sees a half-deleted state.
 *
 * Auto-transfers are NOT cleared here — callers should re-run the auto-
 * transfer builder after any add/remove since the graph crosses systems.
 */
export async function deleteSystem(systemId: string): Promise<void> {
    const db = await openTransitDB();
    const tx = db.transaction(
        [
            "systems",
            "stops",
            "routes",
            "trips",
            "stopTimes",
            "services",
            "transfersGtfs",
        ],
        "readwrite",
    );

    await tx.objectStore("systems").delete(systemId);
    await deleteByIndex(tx.objectStore("stops").index("by-system"), systemId);
    await deleteByIndex(tx.objectStore("routes").index("by-system"), systemId);
    await deleteByIndex(tx.objectStore("trips").index("by-system"), systemId);
    await deleteByIndex(
        tx.objectStore("stopTimes").index("by-system"),
        systemId,
    );
    await deleteByIndex(
        tx.objectStore("services").index("by-system"),
        systemId,
    );
    // transfersGtfs: by-system is indexed on fromStopId which is prefixed with
    // the systemId. Cursor over the index's keyRange for that prefix.
    const prefix = `${systemId}:`;
    const range = IDBKeyRange.bound(prefix, `${prefix}\uffff`);
    let cursor = await tx
        .objectStore("transfersGtfs")
        .index("by-from")
        .openCursor(range);
    while (cursor) {
        await cursor.delete();
        cursor = await cursor.continue();
    }

    await tx.done;
}

async function deleteByIndex(
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    index: any,
    systemId: string,
): Promise<void> {
    let cursor = await index.openCursor(IDBKeyRange.only(systemId));
    while (cursor) {
        await cursor.delete();
        cursor = await cursor.continue();
    }
}

// ---------------------------------------------------------------------------
// Bulk writes for import
// ---------------------------------------------------------------------------

/**
 * Write everything for one system atomically. If any put fails the whole
 * transaction rolls back — we never leave a half-imported feed on disk.
 */
export async function writeSystemBulk(opts: {
    system: TransitSystem;
    stops: TransitStop[];
    routes: TransitRoute[];
    trips: TransitTrip[];
    stopTimes: TransitTripStopTimes[];
    services: TransitService[];
    transfers: Footpath[];
}): Promise<void> {
    const db = await openTransitDB();
    const tx = db.transaction(
        [
            "systems",
            "stops",
            "routes",
            "trips",
            "stopTimes",
            "services",
            "transfersGtfs",
        ],
        "readwrite",
    );

    const put = <T>(store: string, items: T[]) => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const os = (tx as any).objectStore(store);
        return Promise.all(items.map((item) => os.put(item)));
    };

    await tx.objectStore("systems").put(opts.system);
    await put("stops", opts.stops);
    await put("routes", opts.routes);
    await put("trips", opts.trips);
    await put("stopTimes", opts.stopTimes);
    await put("services", opts.services);
    await put("transfersGtfs", opts.transfers);

    await tx.done;
}

// ---------------------------------------------------------------------------
// Reads used by routing
// ---------------------------------------------------------------------------

export async function getAllStops(systemIds?: string[]): Promise<TransitStop[]> {
    const db = await openTransitDB();
    if (!systemIds || systemIds.length === 0) {
        return db.getAll("stops");
    }
    const out: TransitStop[] = [];
    for (const sid of systemIds) {
        out.push(...(await db.getAllFromIndex("stops", "by-system", sid)));
    }
    return out;
}

export async function getAllStopTimes(
    systemIds?: string[],
): Promise<TransitTripStopTimes[]> {
    const db = await openTransitDB();
    if (!systemIds || systemIds.length === 0) {
        return db.getAll("stopTimes");
    }
    const out: TransitTripStopTimes[] = [];
    for (const sid of systemIds) {
        out.push(...(await db.getAllFromIndex("stopTimes", "by-system", sid)));
    }
    return out;
}

export async function getAllTrips(systemIds?: string[]): Promise<TransitTrip[]> {
    const db = await openTransitDB();
    if (!systemIds || systemIds.length === 0) {
        return db.getAll("trips");
    }
    const out: TransitTrip[] = [];
    for (const sid of systemIds) {
        out.push(...(await db.getAllFromIndex("trips", "by-system", sid)));
    }
    return out;
}

export async function getAllServices(
    systemIds?: string[],
): Promise<TransitService[]> {
    const db = await openTransitDB();
    if (!systemIds || systemIds.length === 0) {
        return db.getAll("services");
    }
    const out: TransitService[] = [];
    for (const sid of systemIds) {
        out.push(...(await db.getAllFromIndex("services", "by-system", sid)));
    }
    return out;
}

export async function getAllTransfers(): Promise<Footpath[]> {
    const db = await openTransitDB();
    const [gtfs, auto] = await Promise.all([
        db.getAll("transfersGtfs"),
        db.getAll("transfersAuto"),
    ]);
    return [...gtfs, ...auto];
}

// ---------------------------------------------------------------------------
// Auto-transfer management
// ---------------------------------------------------------------------------

export async function replaceAutoTransfers(
    transfers: Footpath[],
): Promise<void> {
    const db = await openTransitDB();
    const tx = db.transaction("transfersAuto", "readwrite");
    await tx.objectStore("transfersAuto").clear();
    await Promise.all(
        transfers.map((t) => tx.objectStore("transfersAuto").put(t)),
    );
    await tx.done;
}

// ---------------------------------------------------------------------------
// Diagnostics — used by the Transit Systems dialog to show space usage
// ---------------------------------------------------------------------------

export async function estimateUsage(): Promise<{
    usage?: number;
    quota?: number;
}> {
    if (
        typeof navigator === "undefined" ||
        !navigator.storage?.estimate
    ) {
        return {};
    }
    const { usage, quota } = await navigator.storage.estimate();
    return { usage, quota };
}
